- name: Adding group {{ groupname }}
  ansible.builtin.group:
    name: "{{ groupname }}"
    state: present

- name: Adding group {{ groupname }} with custom gid
  ansible.builtin.group:
    name: "{{ groupname }}"
    state: present
    gid: "{{ customgid }}"
