- name: Installing prerequisite packages  python3-pip on Ubuntu  before  taking backup
  apt:
    name:
    - python3-pip
    - python3-mysqldb
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Installing  prerequisite pymysql dependencies before taking backup
  ansible.builtin.pip:
    name:
    - pymysql

- name: Ensure backup directory exists for taking backup on dev server
  ansible.builtin.file:
    path: /opt/backups/{{ ansible_date_time.date }}
    state: directory
    mode: 0755


- name: Taking  backup on dev server for all databases
  community.mysql.mysql_db:
    state: dump
    name: all
    login_user: "{{ dbusername }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_host: "{{ dbhost }}"
    login_password: "{{ dbpassword }}"
    target: /opt/backups/{{ ansible_date_time.date }}/alldb.sql


